const ChatList = [
    {
      id: 0,
      img: "",
      name: "JJ",
      ticket: "465421",
      time: "9:36",
      unread: 0,
      pinned: true,
      online: true,
    },
    {
      id: 1,
      img: "",
      name: "James",
      ticket: "456322",
      time: "12:02",
      unread: 2,
      pinned: true,
      online: false,
    },
    {
      id: 2,
      img: "",
      name: "Vence",
      ticket: "789546",
      time: "10:35",
      unread: 3,
      pinned: false,
      online: true,
    },
    {
      id: 3,
      img: "",
      name: "Klyde",
      ticket: "456254",
      time: "04:00",
      unread: 0,
      pinned: false,
      online: true,
    },
    {
      id: 4,
      img: "",
      name: "Xia",
      ticket: "745621",
      time: "08:42",
      unread: 0,
      pinned: false,
      online: false,
    },
    {
      id: 5,
      img: "",
      name: "Abby",
      ticket: "456215",
      time: "08:42",
      unread: 0,
      pinned: false,
      online: false,
    },
    {
      id: 6,
      img: "",
      name: "Blaise",
      ticket: "785621",
      time: "08:42",
      unread: 0,
      pinned: false,
      online: false,
    },
    {
      id: 7,
      img: "",
      name: "Sam",
      ticket: "458932",
      time: "08:42",
      unread: 0,
      pinned: false,
      online: false,
    },
  ];

  export {
    ChatList
  };